#  include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: ignore
    unused_local_variable: ignore
    unused_field: ignore
    unused_element: ignore
    unnecessary_null_comparison: ignore
    must_be_immutable: ignore
    deprecated_member_use: ignore
linter:
  rules:
    # unused_import: false

